makeFile: main.c HelperFunctions.c Parser.c ShortestPathAlgorithms.c TestBench.c Simulator.c GlobalVariables.h Simulator.h TestBench.h ShortestPathAlgorithms.h Parser.h HelperFunctions.h
	clang *.c -lm

